import "./style.css";
import "./index.css";
import "./function1";
import "./function2";
import "./function3";
import "./function4";
import "./typescript_level_01";
import "./typescript_level_02";
import "./vat_calculator";
// let name: string = "Alice";
// let age: number = 25;
// let isStudent: boolean = true;
// console.log(name);
// console.log(age);
// console.log(isStudent);
// // array of numbers
// let numbers: number[] = [1, 2, 3, 4, 5];
// let myArray = ["hello", 42, true, { key: "value" }, [1, 2, 3]];
// console.log(numbers);
// console.log(myArray);
